### PR TITLE
Add type definition for command args

### PR DESCRIPTION
**Pull request by Samuel-Martineau**
This pull request uses Typescript [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) to parse the command string and provide type-checking for the `args` of the execute function based on the format defined in the README. It supports `optional` and `required` parameter, as well as explicit type definition (for `Float`, `Int` and `GuildMember`) and `rest` parameters.

I think this _Pull Request_ has the potential to make it easier to use this library in a Typescript environment, as casting the arguments is no longer necessary for the developer.

### CODE REVIEW

**Comment by wwselleck** [comment]
Thanks for the contribution! I'm not very familiar with Template Literal Types, so I'm gonna do some reading and I'll come back to review this soon.

**Comment by wwselleck** [comment]
Looks good! I'm pleasantly surprised that the command strings can be statically typed like this.

One comment, do you have any ideas for how we might test that this type is correct? e.g., provide some example command strings and somehow assert that the generated CommandArgs type is correct?

**Comment by Samuel-Martineau** [comment]
I have no clue...

**Comment by Samuel-Martineau** [comment]
In a quick google search, I found [this](https://stackoverflow.com/questions/49296151/how-to-write-tests-for-typescript-typing-definition/49361858)

**Comment by wwselleck** [comment]
I just pushed a revert for this PR. I was running into issues when trying to get it working for the default values syntax I was working on, and also would prefer to not have this very complex type in place w/o any tests. It's likely just a lack of familiarity on my part that's causing me to have issues with it, but regardless I don't want it slowing me down as I try to add features. I'll look to get this type added back once I'm closer to a 1.0 feature set.

**Comment by Samuel-Martineau** [comment]
I didn’t mean to cause you trouble! Sorry

**Comment by wwselleck** [comment]
No trouble at all! I'm just not familiar enough with template literal types to keep them updated accurately. I hope to your PR back at some point with whatever changes necessary.

**Pull request merged**
